---
# Include vars for specific OS distribution
- name: Include variables for specific OS family.
  include_vars: "{{ ansible_os_family }}.yml"

# Include tasks for specific OS 
- name: Include tasks for specific OS family.
  include_tasks: "setup-{{ ansible_os_family }}.yml"

