---
# Include vars for specific OS distribution
- name: Include variables for Fedora / Ubuntu / Debian distributions.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Fedora" or
        ansible_distribution == "Ubuntu" or
        ansible_distribution == "Debian"

- name: Include variables for CentOS / RHEL distribution.
  include_vars: "Redhat.yml"
  when: ansible_distribution == "RedHat" or
        ansible_distribution == "Red Hat Enterprise Linux" or
        ansible_distribution == "CentOS"

# Include tasks for specific OS distribution
- name: Include tasks for Ubuntu / Debian distributions.
  include_tasks: "setup-debian-ubuntu.yml"
  when: ansible_distribution == "Ubuntu" or
        ansible_distribution == "Debian"

- name: Include tasks for Fedora distribution.
  include_tasks: "setup-fedora.yml"
  when: ansible_distribution == "Fedora"

- name: Include tasks for CentOS / RHEL distributions.
  include_tasks: "setup-redhat.yml"
  when: ansible_distribution == "RedHat" or
        ansible_distribution == "Red Hat Enterprise Linux" or
        ansible_distribution == "CentOS" 
