---
- name: Remove old versions of docker packages.
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - docker-engine-selinux
      - podman
      - runc
    state: absent
  become: yes

- name: Add Docker yum repository.
  get_url:
    url: "{{ docker_repo }}"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    force: yes
  become: yes

- name: Install Docker Engine.
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes
  notify: Start and enable docker engine
