---
- name: Remove old versions of docker packages.
  yum:
    name:
       - docker
       - docker-client
       - docker-client-latest
       - docker-common
       - docker-latest
       - docker-latest-logrotate
       - docker-logrotate 
       - docker-engine
    state: removed
    become: yes

- name: Add Docker yum repository.
  get_url:
    url: "{{ docker_repo }}"
    dest: "/etc/yum.repos.d/"
  become: yes

- name: Install Docker Engine.
  yum:
   - docker-ce
   - docker-ce-cli
   - containerd.io
  become: yes
  notify: Start and enable docker engine