galaxy_info:
  role_name: docker
  author: Sergiusz Parchatko
  description: Simple ansible role to install docker on various linux distros

  license: BSD-2-Clause

  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
      - 7
      - 8
  - name: Debian
    versions:
      - bullseye
      - buster
  - name: Fedora
    versions:
      - 33
      - 34
  - name: Ubuntu
    versions:
      - bionic
      - focal
      - hirsute

  galaxy_tags: ['docker', 'docker-compose', 'container']
